//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabana.Campo.RAAgricola.WS.RefInterfaceEAM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", ConfigurationName="RefInterfaceEAM.InterfaceEAM_Port")]
    public interface InterfaceEAM_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (InsertDetailsServices_Result) del mensaje InsertDetailsServices_Result no coincide con el valor predeterminado (InsertDetailsServices)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM:InsertDetailsServices", ReplyAction="*")]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices_Result InsertDetailsServices(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (PostShipment_Result) del mensaje PostShipment_Result no coincide con el valor predeterminado (PostShipment)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM:PostShipment", ReplyAction="*")]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment_Result PostShipment(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (PostResource_Result) del mensaje PostResource_Result no coincide con el valor predeterminado (PostResource)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM:PostResource", ReplyAction="*")]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource_Result PostResource(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDetailsServices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class InsertDetailsServices {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string pedidoServicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=1)]
        public int tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=2)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=3)]
        public decimal cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=4)]
        public string bodega;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=5)]
        public string productoServicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=6)]
        public string fase;
        
        public InsertDetailsServices() {
        }
        
        public InsertDetailsServices(string pedidoServicio, int tipo, string codigo, decimal cantidad, string bodega, string productoServicio, string fase) {
            this.pedidoServicio = pedidoServicio;
            this.tipo = tipo;
            this.codigo = codigo;
            this.cantidad = cantidad;
            this.bodega = bodega;
            this.productoServicio = productoServicio;
            this.fase = fase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDetailsServices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class InsertDetailsServices_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string return_value;
        
        public InsertDetailsServices_Result() {
        }
        
        public InsertDetailsServices_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostShipment", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class PostShipment {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=1)]
        public string orderService;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=2)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=3)]
        public string externalDocument;
        
        public PostShipment() {
        }
        
        public PostShipment(string document, string orderService, string user, string externalDocument) {
            this.document = document;
            this.orderService = orderService;
            this.user = user;
            this.externalDocument = externalDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostShipment_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class PostShipment_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string return_value;
        
        public PostShipment_Result() {
        }
        
        public PostShipment_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostResource", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class PostResource {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string orderService;
        
        public PostResource() {
        }
        
        public PostResource(string orderService) {
            this.orderService = orderService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostResource_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", IsWrapped=true)]
    public partial class PostResource_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/InterfaceEAM", Order=0)]
        public string return_value;
        
        public PostResource_Result() {
        }
        
        public PostResource_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceEAM_PortChannel : Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceEAM_PortClient : System.ServiceModel.ClientBase<Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port>, Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port {
        
        public InterfaceEAM_PortClient() {
        }
        
        public InterfaceEAM_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceEAM_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceEAM_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceEAM_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices_Result Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port.InsertDetailsServices(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices request) {
            return base.Channel.InsertDetailsServices(request);
        }
        
        public string InsertDetailsServices(string pedidoServicio, int tipo, string codigo, decimal cantidad, string bodega, string productoServicio, string fase) {
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices inValue = new Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices();
            inValue.pedidoServicio = pedidoServicio;
            inValue.tipo = tipo;
            inValue.codigo = codigo;
            inValue.cantidad = cantidad;
            inValue.bodega = bodega;
            inValue.productoServicio = productoServicio;
            inValue.fase = fase;
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InsertDetailsServices_Result retVal = ((Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port)(this)).InsertDetailsServices(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment_Result Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port.PostShipment(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment request) {
            return base.Channel.PostShipment(request);
        }
        
        public string PostShipment(string document, string orderService, string user, string externalDocument) {
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment inValue = new Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment();
            inValue.document = document;
            inValue.orderService = orderService;
            inValue.user = user;
            inValue.externalDocument = externalDocument;
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostShipment_Result retVal = ((Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port)(this)).PostShipment(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource_Result Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port.PostResource(Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource request) {
            return base.Channel.PostResource(request);
        }
        
        public string PostResource(string orderService) {
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource inValue = new Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource();
            inValue.orderService = orderService;
            Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.PostResource_Result retVal = ((Cabana.Campo.RAAgricola.WS.RefInterfaceEAM.InterfaceEAM_Port)(this)).PostResource(inValue);
            return retVal.return_value;
        }
    }
}
