//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabana.Campo.RAAgricola.WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAI_Purchase_Line
    {
        public byte[] timestamp { get; set; }
        public int Document_Type { get; set; }
        public string Document_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Buy_from_Vendor_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Location_Code { get; set; }
        public string Posting_Group { get; set; }
        public System.DateTime Expected_Receipt_Date { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public string Unit_of_Measure { get; set; }
        public decimal Quantity { get; set; }
        public decimal Outstanding_Quantity { get; set; }
        public decimal Qty__to_Invoice { get; set; }
        public decimal Qty__to_Receive { get; set; }
        public decimal Direct_Unit_Cost { get; set; }
        public decimal Unit_Cost__LCY_ { get; set; }
        public decimal VAT__ { get; set; }
        public decimal Line_Discount__ { get; set; }
        public decimal Line_Discount_Amount { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount_Including_VAT { get; set; }
        public decimal Unit_Price__LCY_ { get; set; }
        public byte Allow_Invoice_Disc_ { get; set; }
        public decimal Gross_Weight { get; set; }
        public decimal Net_Weight { get; set; }
        public decimal Units_per_Parcel { get; set; }
        public decimal Unit_Volume { get; set; }
        public int Appl__to_Item_Entry { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Job_No_ { get; set; }
        public decimal Indirect_Cost__ { get; set; }
        public byte Recalculate_Invoice_Disc_ { get; set; }
        public decimal Outstanding_Amount { get; set; }
        public decimal Qty__Rcd__Not_Invoiced { get; set; }
        public decimal Amt__Rcd__Not_Invoiced { get; set; }
        public decimal Quantity_Received { get; set; }
        public decimal Quantity_Invoiced { get; set; }
        public string Receipt_No_ { get; set; }
        public int Receipt_Line_No_ { get; set; }
        public decimal Profit__ { get; set; }
        public string Pay_to_Vendor_No_ { get; set; }
        public decimal Inv__Discount_Amount { get; set; }
        public string Vendor_Item_No_ { get; set; }
        public string Sales_Order_No_ { get; set; }
        public int Sales_Order_Line_No_ { get; set; }
        public byte Drop_Shipment { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public int VAT_Calculation_Type { get; set; }
        public string Transaction_Type { get; set; }
        public string Transport_Method { get; set; }
        public int Attached_to_Line_No_ { get; set; }
        public string Entry_Point { get; set; }
        public string Area { get; set; }
        public string Transaction_Specification { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string Tax_Group_Code { get; set; }
        public byte Use_Tax { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public decimal Outstanding_Amount__LCY_ { get; set; }
        public decimal Amt__Rcd__Not_Invoiced__LCY_ { get; set; }
        public string Blanket_Order_No_ { get; set; }
        public int Blanket_Order_Line_No_ { get; set; }
        public decimal VAT_Base_Amount { get; set; }
        public decimal Unit_Cost { get; set; }
        public byte System_Created_Entry { get; set; }
        public decimal Line_Amount { get; set; }
        public decimal VAT_Difference { get; set; }
        public decimal Inv__Disc__Amount_to_Invoice { get; set; }
        public string VAT_Identifier { get; set; }
        public int IC_Partner_Ref__Type { get; set; }
        public string IC_Partner_Reference { get; set; }
        public decimal Prepayment__ { get; set; }
        public decimal Prepmt__Line_Amount { get; set; }
        public decimal Prepmt__Amt__Inv_ { get; set; }
        public decimal Prepmt__Amt__Incl__VAT { get; set; }
        public decimal Prepayment_Amount { get; set; }
        public decimal Prepmt__VAT_Base_Amt_ { get; set; }
        public decimal Prepayment_VAT__ { get; set; }
        public int Prepmt__VAT_Calc__Type { get; set; }
        public string Prepayment_VAT_Identifier { get; set; }
        public string Prepayment_Tax_Area_Code { get; set; }
        public byte Prepayment_Tax_Liable { get; set; }
        public string Prepayment_Tax_Group_Code { get; set; }
        public decimal Prepmt_Amt_to_Deduct { get; set; }
        public decimal Prepmt_Amt_Deducted { get; set; }
        public byte Prepayment_Line { get; set; }
        public decimal Prepmt__Amount_Inv__Incl__VAT { get; set; }
        public decimal Prepmt__Amount_Inv___LCY_ { get; set; }
        public string IC_Partner_Code { get; set; }
        public decimal Prepmt__VAT_Amount_Inv___LCY_ { get; set; }
        public decimal Prepayment_VAT_Difference { get; set; }
        public decimal Prepmt_VAT_Diff__to_Deduct { get; set; }
        public decimal Prepmt_VAT_Diff__Deducted { get; set; }
        public decimal Outstanding_Amt__Ex__VAT__LCY_ { get; set; }
        public decimal A__Rcd__Not_Inv__Ex__VAT__LCY_ { get; set; }
        public int Dimension_Set_ID { get; set; }
        public string Job_Task_No_ { get; set; }
        public int Job_Line_Type { get; set; }
        public decimal Job_Unit_Price { get; set; }
        public decimal Job_Total_Price { get; set; }
        public decimal Job_Line_Amount { get; set; }
        public decimal Job_Line_Discount_Amount { get; set; }
        public decimal Job_Line_Discount__ { get; set; }
        public decimal Job_Unit_Price__LCY_ { get; set; }
        public decimal Job_Total_Price__LCY_ { get; set; }
        public decimal Job_Line_Amount__LCY_ { get; set; }
        public decimal Job_Line_Disc__Amount__LCY_ { get; set; }
        public decimal Job_Currency_Factor { get; set; }
        public string Job_Currency_Code { get; set; }
        public int Job_Planning_Line_No_ { get; set; }
        public decimal Job_Remaining_Qty_ { get; set; }
        public decimal Job_Remaining_Qty___Base_ { get; set; }
        public string Deferral_Code { get; set; }
        public System.DateTime Returns_Deferral_Start_Date { get; set; }
        public string Prod__Order_No_ { get; set; }
        public string Variant_Code { get; set; }
        public string Bin_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity__Base_ { get; set; }
        public decimal Outstanding_Qty___Base_ { get; set; }
        public decimal Qty__to_Invoice__Base_ { get; set; }
        public decimal Qty__to_Receive__Base_ { get; set; }
        public decimal Qty__Rcd__Not_Invoiced__Base_ { get; set; }
        public decimal Qty__Received__Base_ { get; set; }
        public decimal Qty__Invoiced__Base_ { get; set; }
        public System.DateTime FA_Posting_Date { get; set; }
        public int FA_Posting_Type { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public decimal Salvage_Value { get; set; }
        public byte Depr__until_FA_Posting_Date { get; set; }
        public byte Depr__Acquisition_Cost { get; set; }
        public string Maintenance_Code { get; set; }
        public string Insurance_No_ { get; set; }
        public string Budgeted_FA_No_ { get; set; }
        public string Duplicate_in_Depreciation_Book { get; set; }
        public byte Use_Duplication_List { get; set; }
        public string Responsibility_Center { get; set; }
        public string Cross_Reference_No_ { get; set; }
        public string Unit_of_Measure__Cross_Ref__ { get; set; }
        public int Cross_Reference_Type { get; set; }
        public string Cross_Reference_Type_No_ { get; set; }
        public string Item_Category_Code { get; set; }
        public byte Nonstock { get; set; }
        public string Purchasing_Code { get; set; }
        public string Product_Group_Code { get; set; }
        public byte Special_Order { get; set; }
        public string Special_Order_Sales_No_ { get; set; }
        public int Special_Order_Sales_Line_No_ { get; set; }
        public byte Completely_Received { get; set; }
        public System.DateTime Requested_Receipt_Date { get; set; }
        public System.DateTime Promised_Receipt_Date { get; set; }
        public string Lead_Time_Calculation { get; set; }
        public string Inbound_Whse__Handling_Time { get; set; }
        public System.DateTime Planned_Receipt_Date { get; set; }
        public System.DateTime Order_Date { get; set; }
        public byte Allow_Item_Charge_Assignment { get; set; }
        public decimal Return_Qty__to_Ship { get; set; }
        public decimal Return_Qty__to_Ship__Base_ { get; set; }
        public decimal Return_Qty__Shipped_Not_Invd_ { get; set; }
        public decimal Ret__Qty__Shpd_Not_Invd__Base_ { get; set; }
        public decimal Return_Shpd__Not_Invd_ { get; set; }
        public decimal Return_Shpd__Not_Invd___LCY_ { get; set; }
        public decimal Return_Qty__Shipped { get; set; }
        public decimal Return_Qty__Shipped__Base_ { get; set; }
        public string Return_Shipment_No_ { get; set; }
        public int Return_Shipment_Line_No_ { get; set; }
        public string Return_Reason_Code { get; set; }
        public decimal Tax_To_Be_Expensed { get; set; }
        public string Provincial_Tax_Area_Code { get; set; }
        public byte IRS_1099_Liable { get; set; }
        public int GST_HST { get; set; }
        public string SubSource { get; set; }
        public int Transport_Cost_Entry_No { get; set; }
        public int Document_Line_No_ { get; set; }
        public decimal Original_Quantity { get; set; }
        public byte Allow_Quantity_Change { get; set; }
        public string Supply_Chain_Group_Code { get; set; }
        public string Lot_No_ { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Supplier_Lot_No_ { get; set; }
        public int Alt__Qty__Transaction_No_ { get; set; }
        public decimal Quantity__Alt__ { get; set; }
        public decimal Qty__to_Receive__Alt__ { get; set; }
        public decimal Qty__Received__Alt__ { get; set; }
        public decimal Qty__to_Invoice__Alt__ { get; set; }
        public decimal Qty__Invoiced__Alt__ { get; set; }
        public decimal Return_Qty__to_Ship__Alt__ { get; set; }
        public decimal Return_Qty__Shipped__Alt__ { get; set; }
        public byte Alt__Qty__Update_Required { get; set; }
        public decimal Accrual_Amount__Cost_ { get; set; }
        public int Accrual_Plan_Type { get; set; }
        public string Accrual_Source_No_ { get; set; }
        public int Accrual_Source_Doc__Type { get; set; }
        public string Accrual_Source_Doc__No_ { get; set; }
        public int Accrual_Source_Doc__Line_No_ { get; set; }
        public string Scheduled_Accrual_No_ { get; set; }
        public decimal Qty__to_Ship_Recv___Cont__ { get; set; }
        public string Receiving_Reason_Code { get; set; }
        public string Farm { get; set; }
        public string Brand { get; set; }
        public string Country_Region_of_Origin_Code { get; set; }
        public string Commodity_Manifest_No_ { get; set; }
        public int Commodity_Manifest_Line_No_ { get; set; }
        public System.DateTime Commodity_Received_Date { get; set; }
        public string Comm__Payment_Class_Code { get; set; }
        public byte Commodity_Cost_Calculated { get; set; }
        public decimal Commodity_Unit_Cost { get; set; }
        public decimal Commodity_Amount { get; set; }
        public string Commodity_Received_Lot_No_ { get; set; }
        public int Commodity_P_O__Type { get; set; }
        public string Producer_Zone_Code { get; set; }
        public int Rejection_Action { get; set; }
        public string Label_Unit_of_Measure_Code { get; set; }
        public string Work_Order_No_ { get; set; }
        public int Maintenance_Entry_Type { get; set; }
        public string Maintenance_Trade_Code { get; set; }
        public decimal Hours { get; set; }
        public string Part_No_ { get; set; }
        public string Routing_No_ { get; set; }
        public string Operation_No_ { get; set; }
        public string Work_Center_No_ { get; set; }
        public byte Finished { get; set; }
        public int Prod__Order_Line_No_ { get; set; }
        public decimal Overhead_Rate { get; set; }
        public byte MPS_Order { get; set; }
        public int Planning_Flexibility { get; set; }
        public string Safety_Lead_Time { get; set; }
        public int Routing_Reference_No_ { get; set; }



        public void ini(decimal cantidad, decimal monto, string proveedor, string grupoInventario, string grupoProveedor, string tipoIva, int IVA)
        {
            decimal costoUnitario;
            if (cantidad == 0)
            {
                costoUnitario = monto;
            }
            else
            {
                costoUnitario = monto / cantidad;
            }
            Document_Type = 2;
            //Document_No_ = encabezado.No;
            //Line_No_ = 10000 * (j + 1); //10000
            Pay_to_Vendor_No_ = proveedor;// "ACRUZ002";
            Buy_from_Vendor_No_ = proveedor;// "ACRUZ002";
            Type = 1;
            //No_ = ds.SubirReintegroDeta[j].Cuenta;// "11040301";
            Unit_of_Measure_Code = "";
            Location_Code = "";
            Location_Code = "";
            Posting_Group = grupoInventario;// "M.PRIMA";
            Gen__Prod__Posting_Group = grupoInventario;// "M.PRIMA";
            Posting_Group = "";
            Gen__Prod__Posting_Group = grupoInventario;
            Expected_Receipt_Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            Description = "Descripcion";
            Description_2 = "";
            Unit_of_Measure = "";
            Unit_of_Measure = "";
            VAT_Bus__Posting_Group = grupoProveedor;// "PROV.CANER";
            VAT_Prod__Posting_Group = tipoIva;// "SIN-I";
            VAT_Identifier = tipoIva;// "SIN-I";
            Gen__Bus__Posting_Group = grupoProveedor;// "PROV.CANER";
            Shortcut_Dimension_1_Code = "";
            Shortcut_Dimension_2_Code = "";
            Dimension_Set_ID = 0;
            Quantity = cantidad;
            Outstanding_Quantity = cantidad;
            Qty__to_Invoice = cantidad;
            Qty__to_Receive = cantidad;
            Direct_Unit_Cost = costoUnitario;// 1000; //Cantidad
            Unit_Cost__LCY_ = costoUnitario;// 1000; //Cantidad
            VAT__ = IVA; ;
            Line_Discount__ = 0;
            Line_Discount_Amount = 0;
            Amount = monto;// 1000; //Cantidad
            Amount_Including_VAT = monto * (1 + IVA / 100);// 1000; //Cantidad
            Unit_Price__LCY_ = 0;
            Allow_Invoice_Disc_ = 0;
            Gross_Weight = 0;
            Net_Weight = 0;
            Units_per_Parcel = 0;
            Unit_Volume = 0;
            Appl__to_Item_Entry = 0;
            Job_No_ = "";
            Indirect_Cost__ = 0;
            Recalculate_Invoice_Disc_ = 1;
            Outstanding_Amount = Amount_Including_VAT;// 1000; //Cantidad
            Qty__Rcd__Not_Invoiced = 0;
            Amt__Rcd__Not_Invoiced = 0;
            Quantity_Received = 0;
            Quantity_Invoiced = 0;
            Receipt_No_ = "";
            Receipt_Line_No_ = 0;
            Profit__ = 0;
            Inv__Discount_Amount = 0;
            Vendor_Item_No_ = "";
            Sales_Order_No_ = "";
            Sales_Order_Line_No_ = 0;
            Drop_Shipment = 0;
            VAT_Calculation_Type = 0;
            Transaction_Type = "";
            Transport_Method = "";
            Attached_to_Line_No_ = 0;
            Entry_Point = "";
            Area = "";
            Transaction_Specification = "";
            Tax_Area_Code = "";
            Tax_Liable = 0;
            Tax_Group_Code = "";
            Use_Tax = 0;
            Currency_Code = "";
            Outstanding_Amount__LCY_ = Amount_Including_VAT;// 1000; //Cantidad
            Amt__Rcd__Not_Invoiced__LCY_ = 0;
            Blanket_Order_No_ = "";
            Blanket_Order_Line_No_ = 0;
            VAT_Base_Amount = monto;// 1000; //Cantidad
            Unit_Cost = costoUnitario;// 1000; //Cantidad
            System_Created_Entry = 0;
            Line_Amount = monto;// 1000; //Cantidad
            VAT_Difference = 0;
            Inv__Disc__Amount_to_Invoice = 0;
            IC_Partner_Ref__Type = 0;
            IC_Partner_Reference = "";
            Prepayment__ = 0;
            Prepmt__Line_Amount = 0;
            Prepmt__Amt__Inv_ = 0;
            Prepmt__Amt__Incl__VAT = 0;
            Prepayment_Amount = 0;
            Prepmt__VAT_Base_Amt_ = 0;
            Prepayment_VAT__ = 0;
            Prepmt__VAT_Calc__Type = 0;
            Prepayment_VAT_Identifier = "";
            Prepayment_Tax_Area_Code = "";
            Prepayment_Tax_Liable = 0;
            Prepayment_Tax_Group_Code = "";
            Prepmt_Amt_to_Deduct = 0;
            Prepmt_Amt_Deducted = 0;
            Prepayment_Line = 0;
            Prepmt__Amount_Inv__Incl__VAT = 0;
            Prepmt__Amount_Inv___LCY_ = 0;
            IC_Partner_Code = "";
            Prepmt__VAT_Amount_Inv___LCY_ = 0;
            Prepayment_VAT_Difference = 0;
            Prepmt_VAT_Diff__to_Deduct = 0;
            Prepmt_VAT_Diff__Deducted = 0;
            Outstanding_Amt__Ex__VAT__LCY_ = monto;// 1000; //Cantidad
            Prepmt__Amount_Inv___LCY_ = 0;
            A__Rcd__Not_Inv__Ex__VAT__LCY_ = 0;
            Deferral_Code = "";
            Returns_Deferral_Start_Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            SubSource = "";
            Job_Task_No_ = "";
            Job_Line_Type = 0;
            Job_Unit_Price = 0;
            Job_Total_Price = 0;
            Job_Line_Amount = 0;
            Job_Line_Discount_Amount = 0;
            Job_Line_Discount__ = 0;
            Job_Unit_Price__LCY_ = 0;
            Job_Total_Price__LCY_ = 0;
            Job_Line_Amount__LCY_ = 0;
            Job_Line_Disc__Amount__LCY_ = 0;
            Job_Currency_Factor = 0;
            Job_Currency_Code = "";
            Job_Planning_Line_No_ = 0;
            Job_Remaining_Qty_ = 0;
            Job_Remaining_Qty___Base_ = 0;
            Prod__Order_No_ = "";
            Variant_Code = "";
            Bin_Code = "";
            Qty__per_Unit_of_Measure = 1;
            Quantity__Base_ = cantidad;
            Outstanding_Qty___Base_ = cantidad;
            Qty__to_Invoice__Base_ = cantidad;
            Qty__to_Receive__Base_ = cantidad;
            Qty__Rcd__Not_Invoiced__Base_ = 0;
            Qty__Received__Base_ = 0;
            Qty__Invoiced__Base_ = 0;
            FA_Posting_Date = Convert.ToDateTime("1753-01-01 00:00:00.000");
            FA_Posting_Type = 0;
            Depreciation_Book_Code = "";
            Salvage_Value = 0;
            Depr__until_FA_Posting_Date = 0;
            Depr__Acquisition_Cost = 0;
            Maintenance_Code = "";
            Insurance_No_ = "";
            Budgeted_FA_No_ = "";
            Duplicate_in_Depreciation_Book = "";
            Use_Duplication_List = 0;
            Responsibility_Center = "";
            Cross_Reference_No_ = "";
            Unit_of_Measure__Cross_Ref__ = "";
            Cross_Reference_Type = 0;
            Cross_Reference_Type_No_ = "";
            Item_Category_Code = "";
            Nonstock = 0;
            Purchasing_Code = "";
            Product_Group_Code = "";
            Special_Order = 0;
            Special_Order_Sales_No_ = "";
            Special_Order_Sales_Line_No_ = 0;
            Completely_Received = 0;
            Requested_Receipt_Date = Convert.ToDateTime("1753-01-01 00:00:00.000");
            Promised_Receipt_Date = Convert.ToDateTime("1753-01-01 00:00:00.000");
            Lead_Time_Calculation = "";
            Inbound_Whse__Handling_Time = "";
            Planned_Receipt_Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            Order_Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            Allow_Item_Charge_Assignment = 0;
            Return_Qty__to_Ship = 0;
            Return_Qty__to_Ship__Base_ = 0;
            Return_Qty__Shipped_Not_Invd_ = 0;
            Ret__Qty__Shpd_Not_Invd__Base_ = 0;
            Return_Shpd__Not_Invd_ = 0;
            Return_Shpd__Not_Invd___LCY_ = 0;
            Return_Qty__Shipped = 0;
            Return_Qty__Shipped__Base_ = 0;
            Return_Shipment_No_ = "";
            Return_Shipment_Line_No_ = 0;
            Return_Reason_Code = "";
            Tax_To_Be_Expensed = 0;
            Provincial_Tax_Area_Code = "";
            IRS_1099_Liable = 0;
            GST_HST = 0;
            Routing_No_ = "";
            Operation_No_ = "";
            Work_Center_No_ = "";
            Finished = 0;
            Prod__Order_Line_No_ = 0;
            Overhead_Rate = 0;
            MPS_Order = 0;
            Planning_Flexibility = 0;
            Safety_Lead_Time = "";
            Routing_Reference_No_ = 0;
            Transport_Cost_Entry_No = 0;
            Original_Quantity = cantidad;
            Allow_Quantity_Change = 1;
            Supply_Chain_Group_Code = "";
            Lot_No_ = "";
            Creation_Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            Supplier_Lot_No_ = "";
            Alt__Qty__Transaction_No_ = 0;
            Quantity__Alt__ = 0;
            Qty__to_Receive__Alt__ = 0;
            Qty__Received__Alt__ = 0;
            Qty__to_Invoice__Alt__ = 0;
            Qty__Invoiced__Alt__ = 0;
            Return_Qty__to_Ship__Alt__ = 0;
            Return_Qty__Shipped__Alt__ = 0;
            Alt__Qty__Update_Required = 0;
            Accrual_Amount__Cost_ = 0;
            Accrual_Plan_Type = 0;
            Accrual_Source_No_ = "";
            Accrual_Source_Doc__Type = 0;
            Accrual_Source_Doc__No_ = "";
            Accrual_Source_Doc__Line_No_ = 0;
            Scheduled_Accrual_No_ = "";
            Qty__to_Ship_Recv___Cont__ = 0;
            Receiving_Reason_Code = "";
            Farm = "";
            Brand = "";
            Country_Region_of_Origin_Code = "";
            Commodity_Manifest_No_ = "";
            Commodity_Manifest_Line_No_ = 0;
            Commodity_Received_Date = Convert.ToDateTime("1753-01-01 00:00:00.000");
            Comm__Payment_Class_Code = "";
            Commodity_Cost_Calculated = 0;
            Commodity_Unit_Cost = 0;
            Commodity_Amount = 0;
            Commodity_Received_Lot_No_ = "";
            Commodity_P_O__Type = 0;
            Producer_Zone_Code = "";
            Rejection_Action = 0;
            Label_Unit_of_Measure_Code = "";
            Work_Order_No_ = "";
            Maintenance_Entry_Type = 0;
            Maintenance_Trade_Code = "";
            Hours = 0;
            Part_No_ = "";
            Document_Line_No_ = 10000;

        }
    }
}
